name: Drishti Application Deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '17'

#      - name: test code
#        run: mvn test

      - name: build the application
        working-directory: Shristi
        run: mvn clean package
